### ISSUE TITLE
Generate PostgreSQL tables for raw data

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/housing-17#6]

**Comment by wfriedland** [comment]
Riley has created a Django migration method using the partial SoH data provided by Paige.
This items can be considered closed when:
1) The neighborhood profile information is represented in .csv format
2) Django software is written to represent the neighborhood profile information
3) The Django software and .csv files are accessible via git repo 
4) The Postgres DB from the Django migration can be verified in a virtual machine enviornment
